version: '3.8'
services:
  ethereum:
    image: "ethereum-api"
    build:
      context: .
    command: node app.js
    ports:
      - "3000:3000"
    env_file: "./docker-compose.env"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
  mongo:
    image: mongo
    ports:
      - "27017:27017"